apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: appsheet-clipboard
  description: Allows an AppSheet to write to the browser clipboard 
  annotations:
    github.com/project-slug: lds-ics/appsheet-clipboard
    backstage.io/techdocs-ref: dir:. 
spec:
  type: website
  lifecycle: production
  owner: locakrd-team
  system: appsheet-clipboard
